### ISSUE TITLE
Example Issue

### ISSUE THREAD

**Issue by hbomb79** [hbomb79/digital_website#3]
This is an example issue, Brynn and clayton, please comment

**Comment by ElPresidentai** [comment]
NO!!!!!!!1!!!!

**Comment by hbomb79** [comment]
Waiting on you Brynn...

**Comment by ElPresidentai** [comment]
waiting on you Brynn...

**Comment by hbomb79** [comment]
Brynn, Waiting for you!

**Comment by hbomb79** [comment]
@NinjaSauce, Please comment so we know you have GitHub ready to go.

**Comment by NinjaSauce** [comment]
Hi.

**Comment by hbomb79** [comment]
STAHP
