### ISSUE TITLE
Website Link

### ISSUE THREAD

**Issue by ElPresidentai** [hbomb79/digital_website#6]
What is the link (if there is one) for the website so we can view it and stuffs

**Comment by hbomb79** [comment]
The link to the site is: <a href="http://harryfelton.web44.net/dtech" target="_blank">http://harryfelton.web44.net/dtech</a>

The above link might be moved...

**Comment by hbomb79** [comment]
Check the recent commits I have made here: https://github.com/hbomb79/digital_website/commits/master?author=hbomb79

and here: https://github.com/hbomb79/digital_website/commit/8e15744db0486c6c32d2aa63b1f6376610e035d3

(Closing Issue In 24 Hours)
