### ISSUE TITLE
Loading Animation Bug

### ISSUE THREAD

**Issue by hbomb79** [hbomb79/digital_website#8]
The loading animation bar when using Ajax doesn't work the first time the page is loaded, or after re-enabling animations in the settings pane.

In order to get the bar working again, the inline CSS must be edited to prevent it from interfering with rules in the main.css lines 54 - 119.

**Comment by hbomb79** [comment]
Fixed, The above commit resolved

**Comment by NinjaSauce** [comment]
Cool.
